### ISSUE TITLE
Database Maintenance

### ISSUE THREAD

**Issue by amprince01** [snielson/dsapp_python#11] opened 2016-03-17 18:27 UTC
I've run this new version on a new Mobility 2014R2 server and it worked great from cron.

However, after I ran the db maintenance with the -v -i switch, I ran a health check and no maintenance timestamps were recorded.  I know it ran so I'm not worried about it but wanted to make you aware.

**Comment by snielson** [comment] 2016-03-17 20:45
I'll have to do some testing with running the maintenance in cron, and checking the database timestamps.

Just curious.. are you seeing the vacuum and index from the dsapp.log to know it ran, or did you validate with another method?

**Comment by snielson** [comment] 2016-03-17 21:02
I'm not able to duplicate the issue. After the cron ran {dsapp -v -i}, I was able to see the timestamps properly from the health check.

If the cron runs multiple times, do the timestamps ever get updated?

**Comment by amprince01** [comment] 2016-03-17 21:25
It doesn’t appear to be writing the timestamp at all.  The server that I’m testing with is a new 2014R2 server with only 9 users and a handful of devices.  Maybe it’s something different with this version?  The process is going to run tonight on 2 2.01 servers and I can grab logs from all three tomorrow morning for you to see what’s up.

The confirmation that the vacuum and index gets done is in the dsapp.log but when running the General Health Check it doesn’t show it.

BTW, I like the new features! - Noticed right away that for Nightly Maintenance, instead of saying it failed and making go looking for the fact that it doesn’t log if you’re not set to Info or Debug, it was good to see the Warning instead.

Another thing I liked is that it picked up that we needed to run dos2unix on the certificates to clear out the Windows carriage returns.

Thanks.

A

**Comment by snielson** [comment] 2016-03-18 08:36
Thanks for all the support!

I'm curious to see if running the vacuum and index from a terminal work?
First with dsapp -v -i

If that doesn't seem to work, try manually
1. `rcgms stop`
2.` rccron stop`
3. `vacuumdb -U datasync_user datasync --full -v`
4. `vacuumdb -U datasync_user mobility --full -v`
5. `psql -U datasync_user datasync -c "reindex database datasync"`
6. `psql -U datasync_user mobility -c "reindex database mobility"`
7. `rccron start`
8. `rcgms start`

Then check the database manually to see if it has timestamps
`psql -U datasync_user datasync -c "select relname,last_vacuum,date_part('days', now() - last_vacuum) as \"days_ago\" from pg_stat_user_tables;"`

and

`psql -U datasync_user mobility -c "select relname,last_vacuum,date_part('days', now() - last_vacuum) as \"days_ago\" from pg_stat_user_tables;"`

This should tell us if the problem is with dsapp, or postgres itself.

**Comment by snielson** [comment] 2016-08-16 08:55
No reply if manual commands work - Closing as invalid

**Closed by snielson** 2016-08-16 08:55 UTC
Labels: invalid
